version: '3.3'

services:
  ui:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volume/grafana:/var/lib/grafana
    depends_on:
      - db

  db:
    image: influxdb
    ports:
      - "2003:2003"
      - "8086:8086"
      - "8089:8089/udp"
    volumes:
      - ./volume/influxdb:/var/lib/influxdb
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf
