version: '3'

services:
  ui:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volume/grafana:/var/lib/grafana
    depends_on:
      - db

  db:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volume/influxdb:/var/lib/influxdb
